(function() {var implementors = {};
implementors["blender_armature"] = [{text:"impl&lt;'a&gt; Freeze for <a class=\"struct\" href=\"blender_armature/struct.ActionSettings.html\" title=\"struct blender_armature::ActionSettings\">ActionSettings</a>&lt;'a&gt;",synthetic:true,types:["blender_armature::interpolate::ActionSettings"]},{text:"impl&lt;'a&gt; Freeze for <a class=\"struct\" href=\"blender_armature/struct.InterpolationSettings.html\" title=\"struct blender_armature::InterpolationSettings\">InterpolationSettings</a>&lt;'a&gt;",synthetic:true,types:["blender_armature::interpolate::InterpolationSettings"]},{text:"impl Freeze for <a class=\"struct\" href=\"blender_armature/struct.BlenderArmature.html\" title=\"struct blender_armature::BlenderArmature\">BlenderArmature</a>",synthetic:true,types:["blender_armature::BlenderArmature"]},{text:"impl Freeze for <a class=\"struct\" href=\"blender_armature/struct.Keyframe.html\" title=\"struct blender_armature::Keyframe\">Keyframe</a>",synthetic:true,types:["blender_armature::Keyframe"]},{text:"impl Freeze for <a class=\"enum\" href=\"blender_armature/enum.FlattenArmatureError.html\" title=\"enum blender_armature::FlattenArmatureError\">FlattenArmatureError</a>",synthetic:true,types:["blender_armature::export::FlattenArmatureError"]},{text:"impl Freeze for <a class=\"enum\" href=\"blender_armature/enum.BlenderError.html\" title=\"enum blender_armature::BlenderError\">BlenderError</a>",synthetic:true,types:["blender_armature::BlenderError"]},{text:"impl Freeze for <a class=\"enum\" href=\"blender_armature/enum.Bone.html\" title=\"enum blender_armature::Bone\">Bone</a>",synthetic:true,types:["blender_armature::Bone"]},];
implementors["blender_mesh"] = [{text:"impl Freeze for <a class=\"struct\" href=\"blender_mesh/struct.CreateSingleIndexConfig.html\" title=\"struct blender_mesh::CreateSingleIndexConfig\">CreateSingleIndexConfig</a>",synthetic:true,types:["blender_mesh::combine_indices::create_single_index_config::CreateSingleIndexConfig"]},{text:"impl Freeze for <a class=\"struct\" href=\"blender_mesh/struct.BlenderMesh.html\" title=\"struct blender_mesh::BlenderMesh\">BlenderMesh</a>",synthetic:true,types:["blender_mesh::BlenderMesh"]},{text:"impl Freeze for <a class=\"enum\" href=\"blender_mesh/enum.FlattenMeshError.html\" title=\"enum blender_mesh::FlattenMeshError\">FlattenMeshError</a>",synthetic:true,types:["blender_mesh::export::FlattenMeshError"]},{text:"impl Freeze for <a class=\"enum\" href=\"blender_mesh/enum.Channel.html\" title=\"enum blender_mesh::Channel\">Channel</a>",synthetic:true,types:["blender_mesh::material::Channel"]},{text:"impl&lt;U, I&gt; Freeze for <a class=\"enum\" href=\"blender_mesh/enum.MaterialInput.html\" title=\"enum blender_mesh::MaterialInput\">MaterialInput</a>&lt;U, I&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;I: Freeze,<br>&nbsp;&nbsp;&nbsp;&nbsp;U: Freeze,&nbsp;</span>",synthetic:true,types:["blender_mesh::material::MaterialInput"]},{text:"impl Freeze for <a class=\"enum\" href=\"blender_mesh/enum.BlenderError.html\" title=\"enum blender_mesh::BlenderError\">BlenderError</a>",synthetic:true,types:["blender_mesh::BlenderError"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()